// ==================== BAD WORDS CONFIGURATION ====================
// Daftar kata-kata terlarang yang akan difilter oleh auto-moderation
// Tambah atau hapus kata sesuai kebutuhan server Anda
// Semua kata akan dikonversi ke lowercase saat pengecekan

const badWords = [
    // Kata-kata umum
    'toxic',
    'hate',
    'spam',

    // Kata-kata kasar Indonesia
    'anjing',
    'babi',
    'bangsat',
    'kontol',
    'memek',
    'ngentot',
    'ngentod',
    'ngentot',
    'tolol',
    'goblok',
    'bodoh',
    'brengsek',
    'setan',
    'iblis',
    'sialan',
    'jancok',
    'jancuk',
    'asu',
    'kampret',
    'bajingan',
    'berengsek',
    'berengsek',
    'sinting',
    'gila',
    'sakit',
    'coli',
    'colmek',
    'crot',
    'cukimai',
    'dancok',
    'dancuk',
    'entod',
    'entot',
    'ewe',
    'fucking',
    'gelo',
    'genjik',
    'goblog',
    'goblog',
    'itil',
    'jembut',
    'jembud',
    'jilmek',
    'kacung',
    'kafir',
    'kampang',
    'keparat',
    'kimak',
    'kirik',
    'kunyuk',
    'lonte',
    'maho',
    'meki',
    'monyet',
    'ndas',
    'ngewe',
    'ngocok',
    'pantat',
    'pecun',
    'pejuh',
    'peju',
    'pelacur',
    'pelakor',
    'peler',
    'pemerkosa',
    'pendekar',
    'penis',
    'pentil',
    'perek',
    'sarap',
    'silit',
    'sokap',
    'taek',
    'taek',
    'tamvan',
    'telaso',
    'tempik',
    'tempong',
    'tokai',
    'toket',
    'vagina',
    'yidam',

    // Kata-kata Inggris
    'fuck',
    'shit',
    'damn',
    'asshole',
    'bitch',
    'cunt',
    'dick',
    'pussy',
    'nigger',
    'faggot',
    'retard',
    'cancer',
    'die',
    'kill',
    'suicide',
    'rape',
    'pedophile',
    'childporn',
    'cp',
    'loli',
    'hentai'
];

// ==================== EXPORT ====================
module.exports = badWords;
